### PR TITLE
allow to escape assoc-params

### PR DESCRIPTION
**Pull request by skydiablo**
sometimes there are some querys with colones, e.g. in datetime definition like: 
... DATE_FORMAT(su.datetime_from, "%Y-%m-%d %H\:00\:00") ...
so the assoc-params parser will be confused and an invalid sql-query will be created...

### CODE REVIEW

**Review by tonix-tuft — COMMENTED** [review]
What about changing `(?P<assoc_param>[:][a-zA-Z0-9_]+)` to this:

```
(?P<assoc_param>[^0-9a-zA-Z][:][a-zA-Z0-9_]+)
```

?

This way you don't need to escape any characters, which is more compliant with what happens in PHP when using named parameters with PDO.

**Comment by tonix-tuft** [comment]
> What about changing `(?P<assoc_param>[:][a-zA-Z0-9_]+)` to this:
> 
> ```
> (?P<assoc_param>[^0-9a-zA-Z][:][a-zA-Z0-9_]+)
> ```
> 
> ?
> 
> This way you don't need to escape any characters, which is more compliant with what happens in PHP when using named parameters with PDO.

This would be a more correct subpattern for `assoc_param` in my opinion:

```
(?:(?:^|[^0-9a-zA-Z])(?P<assoc_param>[:][a-zA-Z0-9_]+))
```

Check out: https://regex101.com/r/Q73PMb/1/

**Comment by skydiablo** [comment]
okay, so here are some additional tweaks: https://regex101.com/r/05pK9A/1
the only downside is from the first line, the pattern `\W` also include an underscore. maybe back to the long version?

**Comment by tonix-tuft** [comment]
@skydiablo What about using lookbehinds? 

https://regex101.com/r/Hsgr8k/1

This way we will not match the unwanted underscore.

**Comment by tonix-tuft** [comment]
@skydiablo Actually, I don't think we need the negative lookbehind for `_` at all, check https://regex101.com/r/V6cJyl/1

**Comment by tonix-tuft** [comment]
> okay, so here are some additional tweaks: https://regex101.com/r/05pK9A/1 the only downside is from the first line, the pattern `\W` also include an underscore. maybe back to the long version?

Ok, I didn't understand your intentions, now I do. You do want the assoc parameter to be matched if there is an underscore `_`, don't you?

E.g. for you `_:param1` should match, is this what you want? But I don't think there will be queries where the placeholder has a preceeding underscore character, could you make an example?

That said, I would say that your regex https://regex101.com/r/05pK9A/1 is perfectly fine 🙂👌

**Comment by skydiablo** [comment]
the underscore prefix was not my intention, it was your code: https://regex101.com/r/Q73PMb/1/
my tweaks pointet just to this problem but i'm with you, there is no need to handle an underscore. so let us use this version: https://regex101.com/r/05pK9A/1

**Comment by tonix-tuft** [comment]
@skydiablo OK, so I can patch it and release a new patch version on Packagist, or would you like to modify your PR?

**Comment by skydiablo** [comment]
there is no way to add an tag with an pull-request. so please just merge my PR and add an new tag to your repo.

**Comment by tonix-tuft** [comment]
> there is no way to add an tag with an pull-request. so please just merge my PR and add an new tag to your repo.

What if I just change the regex myself and then push a new patch version of this library and just close this PR instead?

Thank you

**Comment by skydiablo** [comment]
hehe ;) okay, just skip my very hard work from the git history so never will ever see my wonderful and great job ;) :D

**Comment by tonix-tuft** [comment]
> hehe ;) okay, just skip my very hard work from the git history so never will ever see my wonderful and great job ;) :D

You pointed out a bug and we found a solution, that's the point of open source and contribution 😉

**Comment by skydiablo** [comment]
Its up to you! It is Your Projekt, so Just bring it in your way.

**Comment by tonix-tuft** [comment]
Hi @skydiablo,

Sorry for the time it took. I have just published version `v1.7.0`! I also added tests with PHPUnit and now this library has 100% coverage.

I ended up using this regex: https://regex101.com/r/Blz9iR/1 .

Thank you! Stay tuned!

**Pull request closed without merging**
